lab_management_system/urls.py
from django.contrib import admin # type: ignore
from django.urls import path,include # type: ignore

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('reservations.urls')),
    # path('lab_tech/', include('reservations.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

reservations/urls.py
from django.urls import path # type: ignore
from django.contrib.auth import views as auth_views # type: ignore
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('home/',views.home_view, name='home'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('equipments/', views.equipments_view, name='equipments'),
    # Update Equipment
    path('equipments/update/<int:equipment_id>/', views.update_equipment_view, name='update_equipment'),
    # Delete equipment
    path('equipment/delete/<int:pk>/', views.delete_equipment_view, name='delete_equipment'),
    # Create equipment vie
    path('equipment/create/', views.create_equipment_view, name='create_equipment'),
    # Create equipment
    path('equipment/new/save', views.create_equipment, name='new_equipment_save'),  
    path('equipments_types/', views.equipments_types_view, name='equipments_types'),
    path('equipments_types/new', views.equipments_types_form_view, name='new_equipment_type'),
     path('create_equipment_type/', views.create_equipment_type, name='create_equipment_type'),
    # Update the equipment type
     path('update/<int:equipment_type_id>/', views.update_equipment_type_view, name='update_equipment_type'),
    path('equipment/<int:pk>/', views.equipment_detail, name='equipment_detail'),
    path('reserve/<int:pk>/', views.reserve_equipment, name='reserve_equipment'),
    path('logout/', views.logout_for_tech, name='logouts'),
    
    
    
    path('', views.home, name='index'),
    
    
    
    # Clients routes
    path('signup/', views.signup, name='signup'),
    path('request_equipment/<int:equipment_id>/', views.request_equipment_view, name='request_equipment_user'),
path('reservations/',views.view_reservations,name='reservations_view'),
path('user_reservations/',views.view_user_reservations,name='client_reservations'),
path('confirm_reservation/<int:reservation_id>/',views.confirm_reservation,name='confirm_reservation'),
 path('mark_return/<int:reservation_id>/', views.mark_return, name='mark_return'),

]

reservations/models.py
from django.db import models # type: ignore
from django.contrib.auth.models import AbstractUser # type: ignore

class LabEquipmentType(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self):
        return self.name

class LabEquipment(models.Model):
    type = models.ForeignKey(LabEquipmentType, on_delete=models.CASCADE, related_name='equipment')
    name = models.CharField(max_length=100)
    description = models.TextField()
    quantity = models.PositiveIntegerField()

    def __str__(self):
        return self.name

class CustomUser(AbstractUser):
    ROLE_CHOICES = (
        ('lab_tech', 'Lab Technician'),
        ('standard', 'Standard User'),
    )
    role = models.CharField(max_length=10, choices=ROLE_CHOICES, default='standard')

class Reservation(models.Model):
    user = models.ForeignKey('CustomUser', on_delete=models.CASCADE)
    equipment = models.ForeignKey(LabEquipment, on_delete=models.CASCADE)
    reserved_quantity = models.PositiveIntegerField()
    reserved_date = models.DateTimeField(auto_now_add=True)
    confirmed = models.BooleanField(default=False)
    is_returned = models.BooleanField(default=False)
    
    def __str__(self):
        return f"{self.user.username} - {self.equipment.name}"

reservations/forms.py
from django import forms # type: ignore
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm # type: ignore
from django.contrib.auth.models import User # type: ignore

from .models import *

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)
    
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class UserLoginForm(AuthenticationForm):
    username = forms.CharField(max_length=254, required=True)
    password = forms.CharField(widget=forms.PasswordInput, required=True)
    
    
class LabEquipmentTypeForm(forms.ModelForm):
    class Meta:
        model = LabEquipmentType
        fields = ['name', 'description']
        
class LabEquipmentForm(forms.ModelForm):
    class Meta:
        model = LabEquipment
        fields = ['name', 'description', 'quantity', 'type']
        
        

class SignUpForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'password1', 'password2')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.role = 'Standard User'  # Set the role to 'standard'
        if commit:
            user.save()
        return user

reservations/views.py
from django.shortcuts import render, get_object_or_404, redirect # type: ignore
from django.contrib import messages # type: ignore
from django.contrib.auth import login, authenticate # type: ignore
from django.contrib.auth.decorators import login_required # type: ignore
from django.utils import timezone # type: ignore
from django.http import JsonResponse # type: ignore
from django.views.decorators.csrf import csrf_exempt # type: ignore

from .models import LabEquipment, LabEquipmentType, Reservation
from .forms import *


def index(request):
    equipment_types = LabEquipmentType.objects.all()
    return render(request, 'reservations/index.html', {'equipment_types': equipment_types})

# Registration
def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account created for {username}!')
            return redirect('login')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form': form})

def user_login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, f'Welcome back, {username}!')
                if user.role == 'lab_tech':
                    return redirect('home')  # Redirect to the home page for lab technicians
                else:
                    return redirect('client')  # Redirect to the client page for standard users
            else:
                messages.error(request, 'Invalid username or password.')
        else:
            messages.error(request, 'Invalid username or password.')
    else:
        form = UserLoginForm()
    return render(request, 'users/login.html', {'form': form})


def home_view (request):
    total_equipments = LabEquipment.objects.count()
    total_reservations = Reservation.objects.count()
    equipment_list = LabEquipment.objects.all() if request.user.is_authenticated and request.user.role == 'standard' else []
    context = {
        'total_equipments': total_equipments,
        'equipment_list': equipment_list,
        'total_reservations': total_reservations
    }
    return render(request,'reservations/home.html',context)

def equipments_view(request):
    equipments = LabEquipment.objects.all()
    return render(request, 'reservations/equipments.html', {'equipments': equipments})


def update_equipment_view(request, equipment_id):
    equipment = get_object_or_404(LabEquipment, pk=equipment_id)
    if request.method == 'POST':
        form = LabEquipmentForm(request.POST, instance=equipment)
        if form.is_valid():
            form.save()
            return redirect('equipments')  # Redirect to the list of equipment
    else:
        form = LabEquipmentForm(instance=equipment)
    return render(request, 'reservations/update_equipment.html', {'form': form})

# Delete equipment Function
def delete_equipment_view(request, pk):
    # Retrieve the equipment object or return 404 if not found
    equipment = get_object_or_404(LabEquipment, pk=pk)

    # Delete the equipment object
    equipment.delete()
    # Redirect to the equipment list page
    return redirect('equipments')  # Replace 'equipment_list' with the name of your equipment list URL pattern

# Create equipment 
def create_equipment_view(request):
    
     # Retrieve all equipment types from the database
    equipment_types = LabEquipmentType.objects.all()

    # Pass the equipment types to the template context
    context = {'equipment_types': equipment_types}


    return render(request,'reservations/new_equipment.html',context)
   
def create_equipment(request):
    name = request.POST.get('name')
    description = request.POST.get('description')
    quantity = 1
    type_id = request.POST.get('type')
    equipment_type = LabEquipmentType.objects.get(pk=type_id)
    # Create a new LabEquipment object
    equipment = LabEquipment.objects.create(
        name=name,
        description=description,
        quantity=quantity,
        type=equipment_type
    )

    # Return a JSON response indicating success
    return redirect('equipments')

def logout_for_tech(request):
    return redirect('login')






# Equipments Typws


def equipments_types_view(request):
    equipments_types = LabEquipmentType.objects.all()
    return render(request,'reservations/equipments_types.html', {'equipments_types':equipments_types})
def equipments_types_form_view(request):
    return render(request,'reservations/new_equipment_type.html')

def new_equipment_type(request):
    if request.method == 'POST':
        form = LabEquipmentTypeForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('equipments_types')  # Redirect to the equipment types page after saving
    else:
        form = LabEquipmentTypeForm()
    return render(request, 'reservations/new_equipment_type.html', {'form': form})


def equipment_detail(request, pk):
    equipment = get_object_or_404(LabEquipment, pk=pk)
    return render(request, 'reservations/equipment_detail.html', {'equipment': equipment})

def create_equipment_type(request):
    if request.method == 'POST':
        data = request.POST
        name = data.get('name')
        description = data.get('description')

        # Validate form data
        if name and description:
            # Create and save LabEquipmentType instance
            equipment_type = LabEquipmentType.objects.create(name=name, description=description)
            return redirect('equipments_types')
        else:
            return JsonResponse({'success': False, 'message': 'Name and description are required'})

    # Handle invalid request method
    return JsonResponse({'success': False, 'message': 'Invalid request method'})

def update_equipment_type_view(request, equipment_type_id):
    equipment_type = get_object_or_404(LabEquipmentType, pk=equipment_type_id)
    if request.method == 'POST':
        form = LabEquipmentTypeForm(request.POST, instance=equipment_type)
        if form.is_valid():
            form.save()
            return redirect('equipments_types')  # Redirect to the list of equipment types
    else:
        form = LabEquipmentTypeForm(instance=equipment_type)
    return render(request, 'reservations/update_equipment_type.html', {'form': form})


@login_required
def reserve_equipment(request, pk):
    equipment = get_object_or_404(LabEquipment, pk=pk)
    if request.method == 'POST':
        reserved_quantity = int(request.POST['reserved_quantity'])
        if reserved_quantity <= equipment.available_quantity:
            reservation = Reservation.objects.create(
                user=request.user,
                equipment=equipment,
                reserved_quantity=reserved_quantity,
                reserved_date=timezone.now()
            )
            equipment.available_quantity -= reserved_quantity
            equipment.save()
            return redirect('index')
    return render(request, 'reservations/reserve_equipment.html', {'equipment': equipment})




























def home(request):
    return render(request, 'indexes.html')




















def signup(request): 
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')  # Redirect to the login page after successful signup
    else:
        form = SignUpForm()
    return render(request, 'registration/register.html', {'form': form})



def request_equipment_view(request, equipment_id):
    # Get the equipment object
    equipment = get_object_or_404(LabEquipment, id=equipment_id)

    # Update equipment quantity to 0
    equipment.quantity = 0
    equipment.save()

    # Create a reservation for the user
    reservation = Reservation.objects.create(
        user=request.user,
        equipment=equipment,
        reserved_quantity=1,
        reserved_date=timezone.now()  # Adjust the time as needed
    )

    # Save the reservation
    reservation.save()

    # Provide a success message
    messages.success(request, 'Equipment requested successfully.')

    # Redirect back to the home page or any other page
    return redirect('equipments')


def view_reservations(request):
     # Fetch all reservations
    reservations = Reservation.objects.all().order_by('-reserved_date')

    # You can further process the reservations or pass them directly to the template
    context = {
        'reservations': reservations
    }

    # Render the template with the reservations data
    return render(request, 'reservations/reservations.html', context)


def confirm_reservation(request,reservation_id):
    # Retrieve the reservation object
    reservation = Reservation.objects.get(id=reservation_id)

    # Confirm the reservation
    reservation.confirmed = True
    reservation.save()

    # Update the stock of the equipment to zero
    equipment = reservation.equipment
    equipment.quantity = 0
    equipment.save()

    # Redirect to a success page or any other appropriate page
    return redirect('reservations_view')


def mark_return(request, reservation_id):
    # Retrieve the reservation object
    reservation = Reservation.objects.get(id=reservation_id)

    # Mark the reservation as returned
    reservation.is_returned = True
    reservation.save()

    # Increment the quantity of the equipment by 1
    equipment = reservation.equipment
    equipment.quantity = 1
    equipment.save()

    # Redirect to a success page or any other appropriate page

reservations/templates/reservations/equipments.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/style.css' %}"
    />
    <title>Reservations</title>
  </head>
  <body>
    <div class="dashboard-container">
      <!-- Sidebar -->
      {% include './left_nav.html' %}

      <!-- Main Content -->
      <div class="main-content">
        <h1>Equipments</h1>
        <div class="btns">
          <a href="{% url 'create_equipment' %}" class="new_btn"> new </a>
        </div>
        <table>
          <thead>
            <tr>
              <th>#</th>
              <th>Name</th>
              <th>Description</th>
              <th>Quantity</th>
              <th>Type</th>
              <th>Availability status</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            {% for equipment in equipments %}
            <tr>
              <td>{{ forloop.counter }}</td>
              <td>{{ equipment.name }}</td>
              <td>{{ equipment.description }}</td>
              <td>{{ equipment.quantity }}</td>
              <td>{{ equipment.type }}</td>
              <td>{{ equipment.quantity|yesno:"Available,Not Available" }}</td>
              <td>
                <a href="{% url 'update_equipment' equipment.id %}">Update</a>
                <a href="{% url 'delete_equipment' equipment.id %}">Delete</a>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </body>
</html>

reservations/templates/reservations/equipments_types.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/style.css' %}"
    />
    <title>Reservations</title>
  </head>
  <body>
    <div class="dashboard-container">
      <!-- Sidebar -->
      {% include './left_nav.html' %}

      <!-- Main Content -->
      <div class="main-content">
        <h1>Equipments types</h1>
        <div class="btns">

        <a href="{% url 'new_equipment_type' %}" class="new_btn">
            New
        </a>
        </div>
        <table>
          <thead>
            <tr>
              <th>#</th>
              <th>Name</th>
              <th>Description</th>
              <th>Quantity</th>
              <th>
                Actions
              </th>
            </tr>
          </thead>
          <tbody>
            {% for equipment_type in equipments_types %}
            <tr>
              <td>{{ forloop.counter }}</td>
              <td>{{ equipment_type.name }}</td>
              <td>{{ equipment_type.description }}</td>
              <td>{{ equipment_type.equipment.count }}</td>
              <td>
                <a href="{% url 'update_equipment_type' equipment_type.id %}">Update</a>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </body>
</html>

reservations/templates/reservations/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/style.css' %}"
    />
    <title>Reservations</title>

    <style></style>
  </head>
  <body>
    {% if user.is_authenticated %}
    <div class="dashboard-container">
      {% include './left_nav.html' %} {% if user.role == 'standard' %}
      <div class="main-content">
        <!-- Welcome message -->
        <h2>Available equipments, "{{user.role}} - {{user.username}}"</h2>
        <p>Now you can request for an equipment.</p>

        <!-- Board displaying totals -->
        <div class="total-boards">
          <div class="total-board">
            <h3>Total Equipments</h3>
            <p>{{ total_equipments }}</p>
          </div>
        </div>
        <!-- Add other total boards as needed -->
      </div>

      {% else %}

      <!-- Main Content -->
      <div class="main-content">
        <!-- Welcome message -->
        <h2>Welcome to the Dashboard, "{{user.role}} - {{user.username}}"</h2>
        <p>
          This is where you can manage your reservations, equipment, and users.
        </p>

        <div class="total-boards">
          <div class="total-board">
            <h3>Total Equipments</h3>
            <p>{{ total_equipments }}</p>
          </div>
          <div class="total-board">
            <h3>Total Reservations</h3>
            <p>{{ total_reservations }}</p>
          </div>
        </div>
      </div>
      {% endif %} {% else %}
      <div class="">User not logged in.</div>
      {% endif %}
    </div>
  </body>
</html>

reservations/templates/reservations/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/style.css' %}"
    />
    <title>Home - Lab Reservation System</title>
    <style>
      /* General Styles */
      body {
        font-family: Arial, sans-serif;
        background-color: #f4f4f9;
        margin: 0;
        padding: 0;
      }

      .container {
        max-width: 1200px;
        margin: 0 auto;
        padding: 20px;
      }

      header {
        background-color: #4caf50;
        color: white;
        padding: 20px 0;
        text-align: center;
      }

      nav {
        text-align: center;
        margin-top: 20px;
      }

      nav a {
        margin: 0 15px;
        text-decoration: none;
        color: #4caf50;
        font-weight: bold;
      }

      section {
        background-color: white;
        padding: 20px;
        margin-top: 20px;
        border-radius: 5px;
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
      }

      h2 {
        color: #333;
      }

      ul {
        list-style-type: disc;
        margin-left: 20px;
      }

      footer {
        text-align: center;
        padding: 10px;
        background-color: #333;
        color: white;
        margin-top: 20px;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <header>
        <h1>Welcome to the Management and Reservation System</h1>
        <p>Welcome, Guest!</p>
      </header>
      <div class="hero">
        <img
          src="{% static './images/bg.jpg' %}"
          alt="Background Image"
          width="100%"
        />
      </div>
      <nav>
        <a href="{% url 'login' %}">Login</a> |
        <a href="{% url 'signup' %}">Create Account</a>
      </nav>

      <section>
        <h2>About Our System</h2>
        <p>
          This system allows lab technicians and standard users to manage lab
          reservations efficiently.
        </p>

        <h2>Features</h2>
        <ul>
          <li>View available equipment</li>
          <li>Reserve lab equipment</li>
          <li>Manage your reservations</li>
          <li>Admin features for lab technicians</li>
        </ul>
      </section>

      <footer>
        <p>&copy; 2024 Lab Reservation System. All rights reserved.</p>
      </footer>
    </div>
  </body>
</html>

reservations/templates/reservations/left_nav.html
<div class="sidebar">
  <ul>
    <li><a href="{% url 'home' %}">Home</a></li>
    <li><a href="{% url 'equipments' %}">Equipments</a></li>
    {% if user.role == 'standard' %}
    <li><a href="{% url 'client_reservations' %}">Reservations</a></li>

    {% else %}
    <li><a href="{% url 'equipments_types' %}">Equipments Types</a></li>
    <li><a href="{% url 'reservations_view' %}">Reservations</a></li>
    {%endif%}
    <form action="{% url 'logouts' %}" method="post" class="logout_form">
      {% csrf_token %}
      <button type="submit">Logout</button>
    </form>

    <!-- Add other sidebar links here -->
  </ul>
</div>

reservations/templates/reservations/new_equipment.html
{% load static %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/style.css' %}"
    />
    <title>Reservations</title>
  </head>
  <body>
    <div class="dashboard-container">
      <!-- Sidebar -->
      {% include './left_nav.html' %}

      <!-- Main Content -->
      <div class="main-content">
        <h1>New equipment</h1>
        <form method="post" action="{% url 'new_equipment_save' %}">
          {% csrf_token %}
          <label for="id_name">Name:</label>
          <input type="text" id="id_name" name="name" required /><br /><br />

          <label for="id_description">Description:</label><br />
          <textarea
            id="id_description"
            name="description"
            rows="4"
            cols="50"
            required
          ></textarea
          ><br /><br />

          <label for="id_type">Type:</label>
          <select id="id_type" name="type" required>
            {% for equipment_type in equipment_types %}
            <option value="{{ equipment_type.id }}">
              {{ equipment_type.name }}
            </option>
            {% endfor %}</select
          ><br /><br />

          <button type="submit">Create</button>
        </form>
      </div>
    </div>
  </body>
</html>

reservations/templates/reservations/new_equipment_type.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/style.css' %}"
    />
    <title>Reservations</title>
  </head>
  <body>
    <div class="dashboard-container">
      <!-- Sidebar -->
      {% include './left_nav.html' %}

      <!-- Main Content -->
      <div class="main-content">
        <h2>Add New Equipment Type</h2>
        <form
          id="equipmentForm"
          method="post"
          action="{% url 'create_equipment_type' %}"
        >
          {% csrf_token %}
          <label for="name">Name:</label>
          <input type="text" id="name" name="name" required /><br /><br />

          <label for="description">Description:</label><br />
          <textarea
            id="description"
            name="description"
            rows="4"
            cols="50"
            required
          ></textarea
          ><br /><br />

          <button type="submit">Submit</button>
        </form>
      </div>
    </div>
  </body>
</html>

reservations/templates/reservations/reservations.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/style.css' %}"
    />
    <title>Reservations</title>
  </head>
  <body>
    <div class="dashboard-container">
      <!-- Sidebar -->
      {% include './left_nav.html' %}

      <!-- Main Content -->
      <div class="main-content">
        <h1>Recent Reservations</h1>
        <div class="btns">
          {% if user.role == '!standard' %}

          <a href="{% url 'create_equipment' %}" class="new_btn"> new </a>
          {%endif%}
        </div>
        <table>
          <thead>
            <tr>
              <th>#</th>
              <th>Equipment</th>
              <th>User</th>
              <th>Requested quantity</th>
              <th>Date & time</th>
              <th>Confirmed?</th>
              <th>Returned?</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            {% for reser in reservations %}
            <tr>
              <td>{{ forloop.counter }}</td>
              <td>{{ reser.equipment }}</td>
              <td>{{ reser.user.username }}</td>
              <td>{{ reser.reserved_quantity }}</td>
              <td>{{ reser.reserved_date }}</td>
              <td>{% if reser.confirmed %}Yes{% else %}No{% endif %}</td>
              <td>{% if reser.is_returned %}Yes{% else %}No{% endif %}</td>

              <td>
                {% if not reser.confirmed %}
                <a href="{% url 'confirm_reservation' reser.id %}">Confirm</a>
                {% elif not reser.is_returned %}
                <a href="{% url 'mark_return' reser.id %}">Mark return</a>
                {% else %} Returned {% endif %}
              </td>
            </tr>

            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </body>
</html>

reservations/templates/reservations/update_equipment.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/style.css' %}"
    />
    <title>Reservations</title>
  </head>
  <body>
    <div class="dashboard-container">
      <!-- Sidebar -->
      {% include './left_nav.html' %}

      <!-- Main Content -->
      <div class="main-content">
        <h2>Update Equipment</h2>
        <form method="POST">
          {% csrf_token %} {{ form.as_p }}
          <button type="submit">Save Changes</button>
        </form>
      </div>
    </div>
  </body>
</html>

reservations/templates/reservations/update_equipment_type.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/style.css' %}"
    />
    <title>Reservations</title>
  </head>
  <body>
    <div class="dashboard-container">
      <!-- Sidebar -->
      {% include './left_nav.html' %}

      <!-- Main Content -->
      <div class="main-content">
        <h2>Update Equipment Type</h2>
        <form method="POST">
          {% csrf_token %} {{ form.as_p }}
          <button type="submit">Save Changes</button>
        </form>
      </div>
    </div>
  </body>
</html>

reservations/templates/reservations/user_reservations.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/style.css' %}"
    />
    <title>Reservations</title>
  </head>
  <body>
    <div class="dashboard-container">
      <!-- Sidebar -->
      {% include './left_nav.html' %}

      <!-- Main Content -->
      <div class="main-content">
        <h1>My  recent Reservations</h1>
        <div class="btns">
          {% if user.role == '!standard' %}

          <a href="{% url 'create_equipment' %}" class="new_btn"> new </a>
          {%endif%}
        </div>
        <table>
          <thead>
            <tr>
              <th>#</th>
              <th>Equipment</th>
              <th>User</th>
              <th>Requested quantity</th>
              <th>Date & time</th>
              <th>Confirmed?</th>
              <th>Returned?</th>
            </tr>
          </thead>
          <tbody>
            {% for reser in user_reservations %}
            <tr>
              <td>{{ forloop.counter }}</td>
              <td>{{ reser.equipment }}</td>
              <td>{{ reser.user.username }}</td>
              <td>{{ reser.reserved_quantity }}</td>
              <td>{{ reser.reserved_date }}</td>
              <td>{% if reser.confirmed %}Yes{% else %}No{% endif %}</td>
              <td>{% if reser.is_returned %}Yes{% else %}No{% endif %}</td>

            
            </tr>

            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </body>
</html>